version: '3.9'

services:
  hka-server-login:
    image: hka-server-login:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app/config:/root/config
    environment:
      - CONFIG_PATH=/root/config/config.json
    restart: always
    depends_on:
      - openldap
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      #LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "HKA-APP"
      LDAP_DOMAIN: "hs-karlsruhe.de"
      LDAP_BASE_DN: "dc=hs-karlsruhe,dc=de"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    #tty: true
    stdin_open: true
    volumes:
      - ./openldap/config:/etc/ldap/slapd.d
      - ./openldap/data:/var/lib/ldap
      # Load .ldif files to extend image config.
      - ./openldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - "8389:389"
      - "8636:636"
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    #domainname: "hs-karlsruhe.de"
    #hostname: "ldap-server"
  phpldapadmin:
      image: osixia/phpldapadmin:latest
      container_name: phpldapadmin
      environment:
        PHPLDAPADMIN_LDAP_HOSTS: "openldap"
        PHPLDAPADMIN_HTTPS: "false"
      ports:
        - "8081:80"
      depends_on:
        - openldap

networks:
  default:
    driver: bridge
